services:
  nextjs:
    build:
      context: ./
      target: dev
      dockerfile: ./Dockerfile
    container_name: mini-project-nextjs
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app/
      - ./node_modules:/usr/src/app/node_modules
    restart: always

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
#networks:
#  frontend_network: